### ISSUE TITLE
Any plan to support blinds

### ISSUE THREAD

**Issue by fotiDim** [jheling/freeathome#1]
Thanks for this add-on! Is there any plan to support window blinds?

**Comment by jheling** [comment]
Sorry for the late response.  It is a bit too hot and i'm enjoying holiday. 
Yes,  my intention is to support the blindactor. But i'm not able to test it, because i don't have the blinds actor.
Do you have blind actors in your free @ home configuration?

**Comment by fotiDim** [comment]
@jheling Yes I have heating and blinds. I will be happy to help with coding with some guidance.

**Comment by fotiDim** [comment]
I am getting this error when adding the config:

```
freeathome:
  host: 192.168.X.X
  username: myuser
  password: mypassword
```


```
Invalid config for [freeathome]: required key not provided @ data['platform']. Got None. (See ?, line ?). Please check the docs at https://home-assistant.io/components/freeathome/
```

**Comment by jheling** [comment]
This evening I will do a clean installation on my raspberry.  Maybe i can
reproduce this error and find a solution.

2018-07-31 11:31 GMT+02:00 Foti Dim <notifications@github.com>:

**Comment by jheling** [comment]
Think i have found the problem. I updated some files in the repository.  If you install the new sources, you should clean up the __pycache__.

**Comment by fotiDim** [comment]
@jheling I think that did the trick. In Home Assistant logs I see 
```
2018-07-31 23:25:20 WARNING (MainThread) [homeassistant.loader] You are using a custom component for freeathome which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
```
which is a good sign.

I have trouble running `get-master-message.py`. I am getting:
```
  File "get-master-message.py", line 71
    yield from self.presence_and_roster()             
             ^
SyntaxError: invalid syntax
```

**Comment by jheling** [comment]
Which Python version are you using? It needs version 3.3 or higher.

2018-07-31 23:29 GMT+02:00 Foti Dim <notifications@github.com>:

**Comment by fotiDim** [comment]
Trying it with Python3 got past this error. Now I am getting:

```
python3 get-master-message.py
Traceback (most recent call last):
  File "get-master-message.py", line 9, in <module>
    from slixmpp.plugins.xep_0009.binding import py2xml, xml2py, xml2fault,
fault2xml
ModuleNotFoundError: No module named 'slixmpp'
```

Note that I am running hass.io in docker and I am trying the command on the
host OS (Ubuntu 18.04) and not in the hass.io container. Do I need to run
it within the container?

**Comment by jheling** [comment]
Im running the get-master-message.py in a windows python session. I have
never tried running this from hasio.
You should use the tool pip to install the slixmpp package (pip install
slixmpp). I have used version 1.3.0 '
For the username in the get-master-message you should use  jid from <ip
adres freeathome>/settings.json.


2018-08-01 14:06 GMT+02:00 Foti Dim <notifications@github.com>:

> Trying it with Python3 got past this error. Now I am getting:
>
> ```
> python3 get-master-message.py
> Traceback (most recent call last):
> File "get-master-message.py", line 9, in <module>
> from slixmpp.plugins.xep_0009.binding import py2xml, xml2py, xml2fault,
> fault2xml
> ModuleNotFoundError: No module named 'slixmpp'
> ```
>
> Note that I am running hass.io in docker and I am trying the command on
> the
> host OS (Ubuntu 18.04) and not in the hass.io container. Do I need to run
> it within the container?
>

**Comment by fotiDim** [comment]
Got it. Python 3.7 was incompatible and I had to downgrade to 3.6. I only altered my kitchen blind.

Blind down:
```
python3 get-master-message.py
INFO      <class 'NoneType'> None
INFO     JID set to: 2ff6f1e9-f7b1-4dd1-b73c-e33b6214b400@busch-jaeger.de/e2fa94c6-307c-46df-a24c-ba086aa4e631
ERROR    Error handling {jabber:client}message stanza
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/slixmpp/xmlstream/xmlstream.py", line 783, in event
    handler_callback(data)
  File "get-master-message.py", line 128, in pub_sub_callback
    log.info(args[0])
IndexError: list index out of range
ERROR    list index out of range
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/slixmpp/xmlstream/xmlstream.py", line 783, in event
    handler_callback(data)
  File "get-master-message.py", line 128, in pub_sub_callback
    log.info(args[0])
IndexError: list index out of range
INFO     <?xml version="1.0" encoding="UTF-8"?><project timeStamp="166163" sessionId="557bbbf" type="update" mrhaVersion="2.1.7" mrhaBuild="5969"><privileges/><devices><device serialNumber="ABB700CFCEE7" domainAddress="930E" state="modified" commissioningState="ready" progress="100"><channels><channel state="modified" i="ch0000" cid="ABB702E7"><inputs/><outputs><dataPoint state="modified" i="odp0010" full="false"><value>30.32</value></dataPoint></outputs><parameters/><scenes/></channel></channels></device></devices></project>

INFO     Rpc callback jhe 
INFO     1
INFO     sysap
INFO     timeSeries
INFO     strings
INFO     definitions
INFO     floorplan
INFO     favorites
INFO     messages
INFO     geoLocations
INFO     sonosPlayers
INFO     sonosFavorites
INFO     descriptions
INFO     devices
INFO       ABB700000000 02BE Sysap FFFF
INFO       ABB700CFCE87 FFFA Raumtemperaturregler 1004
INFO       ABB20C052951 FEFB Jalousieaktor 4-Fach, Reg B001
INFO       ABB700D12312 FFDF Sensor/ Jalousieaktor 1/1-Fach 1013
INFO       ABB2D8D42551 FEFF Heizungsaktor 12-Fach, Reg B004
INFO       ABB700CF922D FFFF Sensoreinheit 1-Fach 1000
INFO       ABB700CFCEE7 FFFA Raumtemperaturregler 1004
INFO       ABB700CE5196 01C0 Sysap Kommunikationsinterface 1012
INFO       ABB700CE5197 01C0 Sysap Kommunikationsinterface 2012
INFO       ABB700CFCEEA FFFA Raumtemperaturregler 1004
INFO       ABB700CFCC0A FFFA Raumtemperaturregler 1004
INFO       ABB700CF9233 FFFF Sensoreinheit 1-Fach 1000
INFO       ABB700CFCC0C FFFA Raumtemperaturregler 1004
INFO       ABB700CFCC0F FFFA Raumtemperaturregler 1004
INFO       ABB700CFCEF2 FFFA Raumtemperaturregler 1004
INFO       ABB700CFCC11 FFFA Raumtemperaturregler 1004
INFO       ABB700CFCC15 FFFA Raumtemperaturregler 1004
INFO       ABB700CF9285 FFFF Sensoreinheit 1-Fach 1000
INFO       ABB700CF9289 FFFF Sensoreinheit 1-Fach 1000
INFO       ABB700D123C7 FFDF Sensor/ Jalousieaktor 1/1-Fach 1013
INFO       ABB209732951 FEFB Jalousieaktor 4-Fach, Reg B001
INFO       ABB700D123C9 FFDF Sensor/ Jalousieaktor 1/1-Fach 1013
INFO       ABB700D1240D FFDF Sensor/ Jalousieaktor 1/1-Fach 1013
INFO       ABB700CF9294 FFFF Sensoreinheit 1-Fach 1000
INFO       FFFF00000003 02AB Zeitprogrammaktor 4A00
INFO       FFFF00000004 0167 Jalousiegruppe 4001
INFO       FFFF00000006 0167 Jalousiegruppe 4001
INFO     <?xml version="1.0" encoding="UTF-8"?><project timeStamp="166164" sessionId="557bbbf" type="update" mrhaVersion="2.1.7" mrhaBuild="5969"><privileges/><devices><device serialNumber="ABB700CFCC0C" domainAddress="930E" state="modified" commissioningState="ready" progress="100"><channels><channel state="modified" i="ch0000" cid="ABB702E7"><inputs/><outputs><dataPoint state="modified" i="odp0010" full="false"><value>29.26</value></dataPoint></outputs><parameters/><scenes/></channel></channels></device></devices></project>

INFO     <?xml version="1.0" encoding="UTF-8"?><project timeStamp="166165" sessionId="557bbbf" type="update" mrhaVersion="2.1.7" mrhaBuild="5969"><sysap><value name="uptime">36205m&#x20;(25d&#x20;3h)</value></sysap><privileges/><devices><device serialNumber="ABB700000000" domainAddress="930E" state="modified" commissioningState="ready"><channels/></device><device serialNumber="ABB209732951" domainAddress="930E" state="modified" commissioningState="ready" progress="100"><channels><channel triggered="true" state="modified" i="ch0002" cid="ABB2050C"><inputs/><outputs/><parameters/><scenes/></channel><channel triggered="true" state="modified" i="ch0003" cid="ABB2050C"><inputs/><outputs/><parameters/><scenes/></channel></channels></device></devices></project>

INFO     <?xml version="1.0" encoding="UTF-8"?><project timeStamp="166166" sessionId="557bbbf" type="update" mrhaVersion="2.1.7" mrhaBuild="5969"><privileges/><devices><device serialNumber="ABB700CFCC0F" domainAddress="930E" state="modified" commissioningState="ready" progress="100"><channels><channel state="modified" i="ch0000" cid="ABB702E7"><inputs/><outputs><dataPoint state="modified" i="odp0010" full="false"><value>28.48</value></dataPoint></outputs><parameters/><scenes/></channel></channels></device></devices></project>

INFO     <?xml version="1.0" encoding="UTF-8"?><project timeStamp="166167" sessionId="557bbbf" type="update" mrhaVersion="2.1.7" mrhaBuild="5969"><privileges/><devices><device serialNumber="ABB2D8D42551" domainAddress="930E" state="modified" commissioningState="ready" progress="100"><channels><channel triggered="true" state="modified" i="ch0009" cid="ABB2030B"><inputs/><outputs/><parameters/><scenes/></channel><channel triggered="true" state="modified" i="ch000A" cid="ABB2030B"><inputs/><outputs/><parameters/><scenes/></channel><channel triggered="true" state="modified" i="ch000B" cid="ABB2030B"><inputs/><outputs/><parameters/><scenes/></channel></channels></device></devices></project>

INFO     <?xml version="1.0" encoding="UTF-8"?><project timeStamp="166168" sessionId="557bbbf" type="update" mrhaVersion="2.1.7" mrhaBuild="5969"><sysap><value name="uptime">36206m&#x20;(25d&#x20;3h)</value></sysap><privileges/><devices><device serialNumber="ABB700000000" domainAddress="930E" state="modified" commissioningState="ready"><channels/></device><device serialNumber="ABB700CFCEF2" domainAddress="930E" state="modified" commissioningState="ready" progress="100"><channels><channel state="modified" i="ch0000" cid="ABB702E7"><inputs/><outputs><dataPoint state="modified" i="odp0010" full="false"><value>30.68</value></dataPoint></outputs><parameters/><scenes/></channel></channels></device></devices></project>

INFO     <?xml version="1.0" encoding="UTF-8"?><project timeStamp="166169" sessionId="557bbbf" type="update" mrhaVersion="2.1.7" mrhaBuild="5969"><privileges/><devices><device serialNumber="ABB20C052951" domainAddress="930E" state="modified" commissioningState="ready"><channels><channel triggered="true" state="modified" i="ch0003" cid="ABB2050C"><inputs/><outputs/><parameters/><scenes/></channel></channels></device></devices></project>

INFO     <?xml version="1.0" encoding="UTF-8"?><project timeStamp="166170" sessionId="557bbbf" type="update" mrhaVersion="2.1.7" mrhaBuild="5969"><privileges/><devices><device serialNumber="ABB700CFCC0F" domainAddress="930E" state="modified" commissioningState="ready" progress="100"><channels><channel state="modified" i="ch0000" cid="ABB702E7"><inputs/><outputs><dataPoint state="modified" i="odp0010" full="false"><value>28.46</value></dataPoint></outputs><parameters/><scenes/></channel></channels></device></devices></project>

INFO     <?xml version="1.0" encoding="UTF-8"?><project timeStamp="166171" sessionId="557bbbf" type="update" mrhaVersion="2.1.7" mrhaBuild="5969"><privileges/><devices><device serialNumber="ABB700CFCEE7" domainAddress="930E" state="modified" commissioningState="ready" progress="100"><channels><channel state="modified" i="ch0000" cid="ABB702E7"><inputs/><outputs><dataPoint state="modified" i="odp0010" full="false"><value>30.3</value></dataPoint></outputs><parameters/><scenes/></channel></channels></device></devices></project>

INFO     <?xml version="1.0" encoding="UTF-8"?><project timeStamp="166172" sessionId="557bbbf" type="update" mrhaVersion="2.1.7" mrhaBuild="5969"><privileges/><devices><device serialNumber="ABB700CFCE87" domainAddress="930E" state="modified" commissioningState="ready" progress="100"><channels><channel state="modified" i="ch0000" cid="ABB702E7"><inputs/><outputs><dataPoint state="modified" i="odp0010" full="false"><value>29.04</value></dataPoint></outputs><parameters/><scenes/></channel></channels></device></devices></project>

INFO     <?xml version="1.0" encoding="UTF-8"?><project timeStamp="166173" sessionId="557bbbf" type="update" mrhaVersion="2.1.7" mrhaBuild="5969"><privileges/><devices><device serialNumber="ABB700CFCC0C" domainAddress="930E" state="modified" commissioningState="ready" progress="100"><channels><channel state="modified" i="ch0000" cid="ABB702E7"><inputs/><outputs><dataPoint state="modified" i="odp0010" full="false"><value>29.24</value></dataPoint></outputs><parameters/><scenes/></channel></channels></device></devices></project>

INFO     <?xml version="1.0" encoding="UTF-8"?><project timeStamp="166174" sessionId="557bbbf" type="update" mrhaVersion="2.1.7" mrhaBuild="5969"><sysap><value name="uptime">36207m&#x20;(25d&#x20;3h)</value></sysap><privileges/><devices><device serialNumber="ABB700000000" domainAddress="930E" state="modified" commissioningState="ready"><channels/></device><device serialNumber="ABB700CFCC0A" domainAddress="930E" state="modified" commissioningState="ready" progress="100"><channels><channel state="modified" i="ch0000" cid="ABB702E7"><inputs/><outputs><dataPoint state="modified" i="odp0010" full="false"><value>29.74</value></dataPoint></outputs><parameters/><scenes/></channel></channels></device></devices></project>

INFO     <?xml version="1.0" encoding="UTF-8"?><project timeStamp="166175" sessionId="557bbbf" type="update" mrhaVersion="2.1.7" mrhaBuild="5969"><privileges/><devices><device serialNumber="ABB700CFCC15" domainAddress="930E" state="modified" commissioningState="ready" progress="100"><channels><channel state="modified" i="ch0000" cid="ABB702E7"><inputs/><outputs><dataPoint state="modified" i="odp0010" full="false"><value>29.28</value></dataPoint></outputs><parameters/><scenes/></channel></channels></device></devices></project>

INFO     <?xml version="1.0" encoding="UTF-8"?><project timeStamp="166176" sessionId="557bbbf" type="update" mrhaVersion="2.1.7" mrhaBuild="5969"><privileges/><devices><device serialNumber="ABB700CFCEE7" domainAddress="930E" state="modified" commissioningState="ready" progress="100"><channels><channel state="modified" i="ch0000" cid="ABB702E7"><inputs/><outputs><dataPoint state="modified" i="odp0010" full="false"><value>30.32</value></dataPoint></outputs><parameters/><scenes/></channel></channels></device></devices></project>

INFO     <?xml version="1.0" encoding="UTF-8"?><project timeStamp="166177" sessionId="557bbbf" type="update" mrhaVersion="2.1.7" mrhaBuild="5969"><sysap><value name="uptime">36207m&#x20;(25d&#x20;3h)</value></sysap><privileges/><devices><device serialNumber="ABB700000000" domainAddress="930E" state="modified" commissioningState="ready"><channels/></device><device serialNumber="ABB700CFCEEA" domainAddress="930E" state="modified" commissioningState="ready" progress="100"><channels><channel state="modified" i="ch0000" cid="ABB702E7"><inputs/><outputs><dataPoint state="modified" i="odp0010" full="false"><value>29.02</value></dataPoint></outputs><parameters/><scenes/></channel></channels></device></devices></project>

INFO     <?xml version="1.0" encoding="UTF-8"?><project timeStamp="166178" sessionId="557bbbf" type="update" mrhaVersion="2.1.7" mrhaBuild="5969"><privileges/><devices><device serialNumber="ABB700CFCC15" domainAddress="930E" state="modified" commissioningState="ready" progress="100"><channels><channel state="modified" i="ch0000" cid="ABB702E7"><inputs/><outputs><dataPoint state="modified" i="odp0010" full="false"><value>29.26</value></dataPoint></outputs><parameters/><scenes/></channel></channels></device></devices></project>

INFO     <?xml version="1.0" encoding="UTF-8"?><project timeStamp="166179" sessionId="557bbbf" type="update" mrhaVersion="2.1.7" mrhaBuild="5969"><privileges/><devices><device serialNumber="ABB2D8D42551" domainAddress="930E" state="modified" commissioningState="ready" progress="100"><channels><channel triggered="true" state="modified" i="ch0009" cid="ABB2030B"><inputs/><outputs/><parameters/><scenes/></channel><channel triggered="true" state="modified" i="ch000A" cid="ABB2030B"><inputs/><outputs/><parameters/><scenes/></channel><channel triggered="true" state="modified" i="ch000B" cid="ABB2030B"><inputs/><outputs/><parameters/><scenes/></channel></channels></device></devices></project>

INFO     <?xml version="1.0" encoding="UTF-8"?><project timeStamp="166180" sessionId="557bbbf" type="update" mrhaVersion="2.1.7" mrhaBuild="5969"><privileges/><devices><device serialNumber="ABB20C052951" domainAddress="930E" state="modified" commissioningState="ready"><channels><channel triggered="true" state="modified" i="ch0003" cid="ABB2050C"><inputs/><outputs/><parameters/><scenes/></channel></channels></device></devices></project>

INFO     <?xml version="1.0" encoding="UTF-8"?><project timeStamp="166181" sessionId="557bbbf" type="update" mrhaVersion="2.1.7" mrhaBuild="5969"><privileges/><devices><device serialNumber="ABB209732951" domainAddress="930E" state="modified" commissioningState="ready" progress="100"><channels><channel triggered="true" state="modified" i="ch0002" cid="ABB2050C"><inputs/><outputs/><parameters/><scenes/></channel><channel triggered="true" state="modified" i="ch0003" cid="ABB2050C"><inputs/><outputs/><parameters/><scenes/></channel></channels></device></devices></project>

INFO     <?xml version="1.0" encoding="UTF-8"?><project timeStamp="166182" sessionId="557bbbf" type="update" mrhaVersion="2.1.7" mrhaBuild="5969"><sysap><value name="uptime">36208m&#x20;(25d&#x20;3h)</value></sysap><privileges/><devices><device serialNumber="ABB700000000" domainAddress="930E" state="modified" commissioningState="ready"><channels/></device><device serialNumber="ABB700CFCEF2" domainAddress="930E" state="modified" commissioningState="ready" progress="100"><channels><channel state="modified" i="ch0000" cid="ABB702E7"><inputs/><outputs><dataPoint state="modified" i="odp0010" full="false"><value>30.66</value></dataPoint></outputs><parameters/><scenes/></channel></channels></device></devices></project>

INFO     <?xml version="1.0" encoding="UTF-8"?><project timeStamp="166183" sessionId="557bbbf" type="update" mrhaVersion="2.1.7" mrhaBuild="5969"><privileges/><devices><device serialNumber="ABB700CFCEEA" domainAddress="930E" state="modified" commissioningState="ready" progress="100"><channels><channel state="modified" i="ch0000" cid="ABB702E7"><inputs/><outputs><dataPoint state="modified" i="odp0010" full="false"><value>29</value></dataPoint></outputs><parameters/><scenes/></channel></channels></device></devices></project>

^CTraceback (most recent call last):
  File "get-master-message.py", line 291, in <module>
    main()
  File "get-master-message.py", line 288, in main
    xmpp.process(forever=True)    
  File "/usr/local/lib/python3.6/site-packages/slixmpp/basexmpp.py", line 212, in process
    XMLStream.process(self, forever=forever, timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/slixmpp/xmlstream/xmlstream.py", line 336, in process
    self.loop.run_forever()
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 422, in run_forever
    self._run_once()
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 1396, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/selectors.py", line 577, in select
    kev_list = self._kqueue.control(None, max_ev, timeout)
KeyboardInterrupt

```

Blind up:
```
INFO      <class 'NoneType'> None
INFO     JID set to: 2ff6f1e9-f7b1-4dd1-b73c-e33b6214b400@busch-jaeger.de/dc47a8c7-1230-4264-82d1-feed0dac7006
ERROR    Error handling {jabber:client}message stanza
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/slixmpp/xmlstream/xmlstream.py", line 783, in event
    handler_callback(data)
  File "get-master-message.py", line 128, in pub_sub_callback
    log.info(args[0])
IndexError: list index out of range
ERROR    list index out of range
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/slixmpp/xmlstream/xmlstream.py", line 783, in event
    handler_callback(data)
  File "get-master-message.py", line 128, in pub_sub_callback
    log.info(args[0])
IndexError: list index out of range
INFO     <?xml version="1.0" encoding="UTF-8"?><project timeStamp="166202" sessionId="557bbbf" type="update" mrhaVersion="2.1.7" mrhaBuild="5969"><privileges/><devices><device serialNumber="FFFF00000004" domainAddress="930E" state="modified" commissioningState="ready"><channels><channel state="modified" i="ch0000" cid="FFFF0202"><inputs><dataPoint state="modified" i="idp0000" full="false"><value>1</value></dataPoint></inputs><outputs/><parameters/><scenes/></channel></channels></device></devices></project>

INFO     Rpc callback jhe 
INFO     1
INFO     sysap
INFO     timeSeries
INFO     strings
INFO     definitions
INFO     floorplan
INFO     favorites
INFO     messages
INFO     geoLocations
INFO     sonosPlayers
INFO     sonosFavorites
INFO     descriptions
INFO     devices
INFO       ABB700000000 02BE Sysap FFFF
INFO       ABB700CFCE87 FFFA Raumtemperaturregler 1004
INFO       ABB20C052951 FEFB Jalousieaktor 4-Fach, Reg B001
INFO       ABB700D12312 FFDF Sensor/ Jalousieaktor 1/1-Fach 1013
INFO       ABB2D8D42551 FEFF Heizungsaktor 12-Fach, Reg B004
INFO       ABB700CF922D FFFF Sensoreinheit 1-Fach 1000
INFO       ABB700CFCEE7 FFFA Raumtemperaturregler 1004
INFO       ABB700CE5196 01C0 Sysap Kommunikationsinterface 1012
INFO       ABB700CE5197 01C0 Sysap Kommunikationsinterface 2012
INFO       ABB700CFCEEA FFFA Raumtemperaturregler 1004
INFO       ABB700CFCC0A FFFA Raumtemperaturregler 1004
INFO       ABB700CF9233 FFFF Sensoreinheit 1-Fach 1000
INFO       ABB700CFCC0C FFFA Raumtemperaturregler 1004
INFO       ABB700CFCC0F FFFA Raumtemperaturregler 1004
INFO       ABB700CFCEF2 FFFA Raumtemperaturregler 1004
INFO       ABB700CFCC11 FFFA Raumtemperaturregler 1004
INFO       ABB700CFCC15 FFFA Raumtemperaturregler 1004
INFO       ABB700CF9285 FFFF Sensoreinheit 1-Fach 1000
INFO       ABB700CF9289 FFFF Sensoreinheit 1-Fach 1000
INFO       ABB700D123C7 FFDF Sensor/ Jalousieaktor 1/1-Fach 1013
INFO       ABB209732951 FEFB Jalousieaktor 4-Fach, Reg B001
INFO       ABB700D123C9 FFDF Sensor/ Jalousieaktor 1/1-Fach 1013
INFO       ABB700D1240D FFDF Sensor/ Jalousieaktor 1/1-Fach 1013
INFO       ABB700CF9294 FFFF Sensoreinheit 1-Fach 1000
INFO       FFFF00000003 02AB Zeitprogrammaktor 4A00
INFO       FFFF00000004 0167 Jalousiegruppe 4001
INFO       FFFF00000006 0167 Jalousiegruppe 4001
INFO     <?xml version="1.0" encoding="UTF-8"?><project timeStamp="166203" sessionId="557bbbf" type="update" mrhaVersion="2.1.7" mrhaBuild="5969"><privileges/><devices><device serialNumber="FFFF00000004" domainAddress="930E" state="modified" commissioningState="ready"><channels><channel state="modified" i="ch0000" cid="FFFF0202"><inputs><dataPoint state="modified" i="idp0001" full="false"><value>50.6</value></dataPoint></inputs><outputs/><parameters/><scenes/></channel></channels></device></devices></project>

INFO     <?xml version="1.0" encoding="UTF-8"?><project timeStamp="166204" sessionId="557bbbf" type="update" mrhaVersion="2.1.7" mrhaBuild="5969"><privileges/><devices><device serialNumber="ABB700CFCC11" domainAddress="930E" state="modified" commissioningState="ready" progress="100"><channels><channel state="modified" i="ch0000" cid="ABB702E7"><inputs/><outputs><dataPoint state="modified" i="odp0010" full="false"><value>28.84</value></dataPoint></outputs><parameters/><scenes/></channel></channels></device></devices></project>

INFO     <?xml version="1.0" encoding="UTF-8"?><project timeStamp="166205" sessionId="557bbbf" type="update" mrhaVersion="2.1.7" mrhaBuild="5969"><privileges/><devices><device serialNumber="ABB700CFCC0C" domainAddress="930E" state="modified" commissioningState="ready" progress="100"><channels><channel state="modified" i="ch0000" cid="ABB702E7"><inputs/><outputs><dataPoint state="modified" i="odp0010" full="false"><value>29.2</value></dataPoint></outputs><parameters/><scenes/></channel></channels></device></devices></project>

INFO     <?xml version="1.0" encoding="UTF-8"?><project timeStamp="166206" sessionId="557bbbf" type="update" mrhaVersion="2.1.7" mrhaBuild="5969"><sysap><value name="uptime">36212m&#x20;(25d&#x20;3h)</value></sysap><privileges/><devices><device serialNumber="ABB700000000" domainAddress="930E" state="modified" commissioningState="ready"><channels/></device><device serialNumber="ABB700CFCC0A" domainAddress="930E" state="modified" commissioningState="ready" progress="100"><channels><channel state="modified" i="ch0000" cid="ABB702E7"><inputs/><outputs><dataPoint state="modified" i="odp0010" full="false"><value>29.72</value></dataPoint></outputs><parameters/><scenes/></channel></channels></device></devices></project>

INFO     <?xml version="1.0" encoding="UTF-8"?><project timeStamp="166207" sessionId="557bbbf" type="update" mrhaVersion="2.1.7" mrhaBuild="5969"><privileges/><devices><device serialNumber="ABB700CFCC15" domainAddress="930E" state="modified" commissioningState="ready" progress="100"><channels><channel state="modified" i="ch0000" cid="ABB702E7"><inputs/><outputs><dataPoint state="modified" i="odp0010" full="false"><value>29.28</value></dataPoint></outputs><parameters/><scenes/></channel></channels></device></devices></project>

INFO     <?xml version="1.0" encoding="UTF-8"?><project timeStamp="166208" sessionId="557bbbf" type="update" mrhaVersion="2.1.7" mrhaBuild="5969"><privileges/><devices><device serialNumber="ABB20C052951" domainAddress="930E" state="modified" commissioningState="ready"><channels><channel triggered="true" state="modified" i="ch0003" cid="ABB2050C"><inputs/><outputs/><parameters/><scenes/></channel></channels></device></devices></project>

INFO     <?xml version="1.0" encoding="UTF-8"?><project timeStamp="166209" sessionId="557bbbf" type="update" mrhaVersion="2.1.7" mrhaBuild="5969"><privileges/><devices><device serialNumber="ABB209732951" domainAddress="930E" state="modified" commissioningState="ready" progress="100"><channels><channel triggered="true" state="modified" i="ch0002" cid="ABB2050C"><inputs/><outputs/><parameters/><scenes/></channel><channel triggered="true" state="modified" i="ch0003" cid="ABB2050C"><inputs/><outputs/><parameters/><scenes/></channel></channels></device></devices></project>

INFO     <?xml version="1.0" encoding="UTF-8"?><project timeStamp="166210" sessionId="557bbbf" type="update" mrhaVersion="2.1.7" mrhaBuild="5969"><privileges/><devices><device serialNumber="ABB700CFCE87" domainAddress="930E" state="modified" commissioningState="ready" progress="100"><channels><channel state="modified" i="ch0000" cid="ABB702E7"><inputs/><outputs><dataPoint state="modified" i="odp0010" full="false"><value>29.04</value></dataPoint></outputs><parameters/><scenes/></channel></channels></device></devices></project>

INFO     <?xml version="1.0" encoding="UTF-8"?><project timeStamp="166211" sessionId="557bbbf" type="update" mrhaVersion="2.1.7" mrhaBuild="5969"><privileges/><devices><device serialNumber="ABB2D8D42551" domainAddress="930E" state="modified" commissioningState="ready" progress="100"><channels><channel triggered="true" state="modified" i="ch0009" cid="ABB2030B"><inputs/><outputs/><parameters/><scenes/></channel><channel triggered="true" state="modified" i="ch000A" cid="ABB2030B"><inputs/><outputs/><parameters/><scenes/></channel><channel triggered="true" state="modified" i="ch000B" cid="ABB2030B"><inputs/><outputs/><parameters/><scenes/></channel></channels></device></devices></project>

INFO     <?xml version="1.0" encoding="UTF-8"?><project timeStamp="166212" sessionId="557bbbf" type="update" mrhaVersion="2.1.7" mrhaBuild="5969"><sysap><value name="uptime">36213m&#x20;(25d&#x20;3h)</value></sysap><privileges/><devices><device serialNumber="ABB700000000" domainAddress="930E" state="modified" commissioningState="ready"><channels/></device><device serialNumber="ABB700CFCC0A" domainAddress="930E" state="modified" commissioningState="ready" progress="100"><channels><channel state="modified" i="ch0000" cid="ABB702E7"><inputs/><outputs><dataPoint state="modified" i="odp0010" full="false"><value>29.74</value></dataPoint></outputs><parameters/><scenes/></channel></channels></device></devices></project>

INFO     <?xml version="1.0" encoding="UTF-8"?><project timeStamp="166213" sessionId="557bbbf" type="update" mrhaVersion="2.1.7" mrhaBuild="5969"><privileges/><devices><device serialNumber="ABB700CFCC15" domainAddress="930E" state="modified" commissioningState="ready" progress="100"><channels><channel state="modified" i="ch0000" cid="ABB702E7"><inputs/><outputs><dataPoint state="modified" i="odp0010" full="false"><value>29.26</value></dataPoint></outputs><parameters/><scenes/></channel></channels></device></devices></project>

^CTraceback (most recent call last):
  File "get-master-message.py", line 291, in <module>
    main()
  File "get-master-message.py", line 288, in main
    xmpp.process(forever=True)    
  File "/usr/local/lib/python3.6/site-packages/slixmpp/basexmpp.py", line 212, in process
    XMLStream.process(self, forever=forever, timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/slixmpp/xmlstream/xmlstream.py", line 336, in process
    self.loop.run_forever()
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 422, in run_forever
    self._run_once()
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 1396, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/selectors.py", line 577, in select
    kev_list = self._kqueue.control(None, max_ev, timeout)
KeyboardInterrupt
```

Does it help?

**Comment by jheling** [comment]
Hello,

I have sent a mail to the email adress of fotidim.com. Can we use private
mail for exchanging files?
I don't want to put untested code on github.

2018-08-01 23:29 GMT+02:00 Foti Dim <notifications@github.com>:
