### ISSUE TITLE
Sporadic issue: Error setting up integration

### ISSUE THREAD

**Issue by itthies** [jheling/freeathome#113]
Hi Team,
my free@home integration is sporadicly not loading.
This is not occuring every time. Mostly, a reboot is fixing this - but that is not a reliable solution ;)

I'm getting this error message in the logs:

```
Logger: homeassistant.config_entries
Source: custom_components/freeathome/fah/pfreeathome.py:531
Integration: Busch Jaeger/ABB Free@Home (documentation)
First occurred: 10:34:27 (1 occurrences)
Last logged: 10:34:27

Error setting up entry 192.168.xxx.yy for freeathome
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/freeathome/__init__.py", line 75, in async_setup_entry
    await sysap.find_devices()
  File "/config/custom_components/freeathome/fah/pfreeathome.py", line 812, in find_devices
    await self.xmpp.find_devices(self._use_room_names)
  File "/config/custom_components/freeathome/fah/pfreeathome.py", line 554, in find_devices
    config = await self.get_config()
  File "/config/custom_components/freeathome/fah/pfreeathome.py", line 531, in get_config
    my_iq = await self.send_rpc_iq('RemoteInterface.getAll', 'de', 2, pretty_value, 0)
slixmpp.exceptions.IqTimeout: <iq id="1ef44706131a4e26ba739a17a54210b8" type="set" to="mrha@busch-jaeger.de/rpc" from="0aae89a5-e51f-4dda-92d2-f4dbd0bd0ffe@busch-jaeger.de"><query xmlns="jabber:iq:rpc"><methodCall><methodName>RemoteInterface.getAll</methodName><params><param><value><string>de</string></value></param><param><value><i4>2</i4></value></param><param><value><i4>0</i4></value></param><param><value><i4>0</i4></value></param></params></methodCall></query></iq>
```

Any idea how to fix this in a permanent way?

**Comment by EnricoBilla** [comment]
Hi, I don't know what the cause could be, maybe a problem in the connection between HA and F@H?

A work-around could be setting the timeout_callback in [L365](https://github.com/jheling/freeathome/blob/92e5cbd3f954f939dde65d0b4683c86d6dde42d9/freeathome/fah/pfreeathome.py#L365) to a reconnect function.
Now I can't test the code, but I will try to open a PR in the next days

**Comment by Tho85** [comment]
Could you provide some information about your setup, e.g. which version of the SysAP do you use, and how many devices are in your f@h installation? Is the SysAP connected via LAN or Wifi?

The response to the `RemoteInterface.getAll` can become quiet large, so I guess this is some kind of network connection problem.

**Comment by alfonsomainardi** [comment]
hello team
my free@home integration is sporadicly not loading

Logger: homeassistant.config_entries
Source: custom_components/freeathome/fah/pfreeathome.py:712
Integration: Busch Jaeger/ABB Free@Home ([documentation](https://github.com/jheling/freeathome))
First occurred: 15:34:31 (1 occurrences)
Last logged: 15:34:31

Error setting up entry 192.168.1.102 for freeathome
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/freeathome/__init__.py", line 77, in async_setup_entry
    await sysap.find_devices()
  File "/config/custom_components/freeathome/fah/pfreeathome.py", line 897, in find_devices
    await self.xmpp.find_devices(self._use_room_names)
  File "/config/custom_components/freeathome/fah/pfreeathome.py", line 712, in find_devices
    filter_mask = int(option.get('mask'), 16) # e.g. '00000001' -> 0x00000001
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by alfonsomainardi** [comment]
2023-01-09 19:32:59.024 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration freeathome which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-01-09 19:34:02.191 WARNING (MainThread) [custom_components.freeathome.fah.pfreeathome] Connection with SysAP lost
2023-01-09 19:34:04.329 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 192.168.1.102 for freeathome
File "/config/custom_components/freeathome/__init__.py", line 77, in async_setup_entry
File "/config/custom_components/freeathome/fah/pfreeathome.py", line 897, in find_devices
File "/config/custom_components/freeathome/fah/pfreeathome.py", line 712, in find_devices
2023-01-10 09:16:30.816 WARNING (MainThread) [custom_components.freeathome.fah.pfreeathome] Connection with SysAP lost
2023-01-10 09:22:22.044 ERROR (MainThread) [custom_components.freeathome.fah.pfreeathome] Free@Home : authentication failed, probably wrong password
2023-01-10 09:22:22.050 WARNING (MainThread) [custom_components.freeathome.fah.pfreeathome] Connection with SysAP lost
2023-01-10 09:22:31.864 WARNING (MainThread) [custom_components.freeathome.fah.pfreeathome] Connection with SysAP lost
2023-01-10 09:22:35.377 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 192.168.1.102 for freeathome
File "/config/custom_components/freeathome/__init__.py", line 77, in async_setup_entry
File "/config/custom_components/freeathome/fah/pfreeathome.py", line 897, in find_devices
File "/config/custom_components/freeathome/fah/pfreeathome.py", line 712, in find_devices
2023-01-10 09:46:30.855 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 192.168.1.102 for freeathome
File "/config/custom_components/freeathome/__init__.py", line 77, in async_setup_entry
File "/config/custom_components/freeathome/fah/pfreeathome.py", line 897, in find_devices
File "/config/custom_components/freeathome/fah/pfreeathome.py", line 712, in find_devices
2023-01-10 09:50:40.095 WARNING (MainThread) [custom_components.freeathome.fah.pfreeathome] Connection with SysAP lost
2023-01-10 09:50:42.942 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 192.168.1.102 for freeathome
File "/config/custom_components/freeathome/__init__.py", line 77, in async_setup_entry
File "/config/custom_components/freeathome/fah/pfreeathome.py", line 897, in find_devices
File "/config/custom_components/freeathome/fah/pfreeathome.py", line 712, in find_devices
