### ISSUE TITLE
Error doing job: Task exception was never retrieved - HACS Repository not available

### ISSUE THREAD

**Issue by Cavekeeper** [jheling/freeathome#127]
On every restart of HA I get the following error:

`Logger: homeassistant
Source: custom_components/freeathome/config_flow.py:50
Integration: Busch Jaeger/ABB Free@Home (documentation)
First occurred: 11:27:31 (1 occurrences)
Last logged: 11:27:31

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/discovery_flow.py", line 74, in _async_process_pending_flows
    await gather_with_concurrency(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 199, in gather_with_concurrency
    return await gather(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 197, in sem_task
    return await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 205, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 232, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 335, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/freeathome/config_flow.py", line 50, in async_step_zeroconf
    if not zeroconf_info.get("name", "").startswith("free@home"):
AttributeError: 'ZeroconfServiceInfo' object has no attribute 'get'`

Then I noticed that freeathome isn´t available as HACS Repository.

Home Assistant Core 2022.6.1
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.1

**Comment by Cavekeeper** [comment]
The last update of fah has fixed the problem.
Also the fah could be installed as hacs custom component.
