### ISSUE TITLE
free@home wireless devices

### ISSUE THREAD

**Issue by crtee** [jheling/freeathome#16]
Hi,

as f@h also has wireless devices available and some (or all?) are not supported by this project yet.

Just adding the device IDs to the list of known IDs didn't do the trick. For example:
"Sensor/ Jalousieaktor 1/1-fach" wireless device with a device ID of "2039" has three channels (ch0009, ch000D and ch0000), the wired one with a device ID of "1013" has only two (ch0003 and ch0000). After discovery, every device with a ch000D shows up twice - once with its given name and once as "ABBXXXXXX/ch000D" (which doesn't do anything). Got it working with just exiting add_cover_device if the channel name is "ch000D", but that's just a very ugly bad hack.

I've got some installed around here (mostly thermostat and cover/blinds actors), so I may be able to provide device IDs or whatever information or help needed. Just let me know.

**Comment by jheling** [comment]
Hello,  
Sorry for the late reaction. 
As  I don't have the wireless FAH devices,  I need other users for test etc. So it is ok to send me your device ID's.  With get-master-message.py you can see what kind of commands are send to the FAH-sysap en what the responses from the FAH-sysap are.  I was hoping that the commands and responses of the wireless devices where the same as the wired devices.
You can reach me with helingj  on google mail.

**Comment by Helldin** [comment]
error then i try, or is it wrong
```
python get-master-message.py 
  File "get-master-message.py", line 71
    yield from self.presence_and_roster()             
             ^
SyntaxError: invalid syntax
```

**Comment by crtee** [comment]
@jheling just sent you some info via mail

**Comment by jheling** [comment]
@Helldin. Are you using python 2? The yield from is introduced with python 3.3

**Comment by Helldin** [comment]
now i get this error

python3 get-master-message.py
INFO     JID set to: installer@busch-jaeger.de/res-371-1772460495-2061955886
INFO     Rpc callback jhe 
ERROR    Error handling {jabber:client}iq stanza
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/slixmpp/xmlstream/xmlstream.py", line 987, in _spawn_event
    handler.run(stanza)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/slixmpp/xmlstream/handler/callback.py", line 76, in run
    self._pointer(payload)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/slixmpp/stanza/iq.py", line 212, in callback_success
    callback(result)
  File "get-master-message.py", line 180, in rpc_callback
    args = xml2py(iq['rpc_query']['method_response']['params'])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/slixmpp/plugins/xep_0009/binding.py", line 95, in xml2py
    for param in params.findall('{%s}param' % namespace):
AttributeError: 'NoneType' object has no attribute 'findall'
ERROR    'NoneType' object has no attribute 'findall'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/slixmpp/xmlstream/xmlstream.py", line 987, in _spawn_event
    handler.run(stanza)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/slixmpp/xmlstream/handler/callback.py", line 76, in run
    self._pointer(payload)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/slixmpp/stanza/iq.py", line 212, in callback_success
    callback(result)
  File "get-master-message.py", line 180, in rpc_callback
    args = xml2py(iq['rpc_query']['method_response']['params'])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/slixmpp/plugins/xep_0009/binding.py", line 95, in xml2py
    for param in params.findall('{%s}param' % namespace):
AttributeError: 'NoneType' object has no attribute 'findall'
ERROR    not-allowed: 
WARNING  You should catch IqError exceptions

**Comment by jheling** [comment]
Is this the lastest version of get-master-message.py? This evening I uploaded a new version. This version uses the username instead of the jid name.

**Comment by Helldin** [comment]
> Is this the lastest version of get-master-message.py? This evening I uploaded a new version. This version uses the username instead of the jid name.

i use the lastet version and only change ip unsername and password on line 301 302 303
i have install slixmpp by do pip3 install slixmpp
then i try to run the  script i get this error

root@nextcloud:/home/ncadmin# python3 get-master-message.py 
INFO     JID set to: installer@busch-jaeger.de/res-310-82397915-1126238426
INFO     Rpc callback jhe 
ERROR    Error handling {jabber:client}iq stanza
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/slixmpp/xmlstream/xmlstream.py", line 987, in _spawn_event
    handler.run(stanza)
  File "/usr/local/lib/python3.6/dist-packages/slixmpp/xmlstream/handler/callback.py", line 76, in run
    self._pointer(payload)
  File "/usr/local/lib/python3.6/dist-packages/slixmpp/stanza/iq.py", line 212, in callback_success
    callback(result)
  File "get-master-message.py", line 181, in rpc_callback
    args = xml2py(iq['rpc_query']['method_response']['params'])
  File "/usr/local/lib/python3.6/dist-packages/slixmpp/plugins/xep_0009/binding.py", line 95, in xml2py
    for param in params.findall('{%s}param' % namespace):
AttributeError: 'NoneType' object has no attribute 'findall'
ERROR    'NoneType' object has no attribute 'findall'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/slixmpp/xmlstream/xmlstream.py", line 987, in _spawn_event
    handler.run(stanza)
  File "/usr/local/lib/python3.6/dist-packages/slixmpp/xmlstream/handler/callback.py", line 76, in run
    self._pointer(payload)
  File "/usr/local/lib/python3.6/dist-packages/slixmpp/stanza/iq.py", line 212, in callback_success
    callback(result)
  File "get-master-message.py", line 181, in rpc_callback
    args = xml2py(iq['rpc_query']['method_response']['params'])
  File "/usr/local/lib/python3.6/dist-packages/slixmpp/plugins/xep_0009/binding.py", line 95, in xml2py
    for param in params.findall('{%s}param' % namespace):
AttributeError: 'NoneType' object has no attribute 'findall'
ERROR    not-allowed: 
WARNING  You should catch IqError exceptions

**Comment by jheling** [comment]
Ok, I see more users with this error. The problem is that I cannot reproduce the error. The error seems to originate in slixmpp.  Can you try an upgrade of slixmpp? (pip install --upgrade slixmpp)?

**Comment by crtee** [comment]
I'm getting the same error as above, running hass.io on RPi3 docker image.
slixmpp should be latest:
```
# pip search slixmpp
slixmpp (1.4.2)        - Slixmpp is an elegant Python library for XMPP (aka Jabber, Google Talk, etc).
  INSTALLED: 1.4.2 (latest)
```

**Comment by jheling** [comment]
@crtee, thank you for finding the source of the errors with get-master-message.py.  It seems that the checks in the new  2.3.0  firmware  are stricter than older versions. I have updated the repository.

**Comment by dbrouwer1979** [comment]
> Hi,
> as f@h also has wireless devices available and some (or all?) are not supported by this project yet.
> Just adding the device IDs to the list of known IDs didn't do the trick. For example:
> "Sensor/ Jalousieaktor 1/1-fach" wireless device with a device ID of "2039" has three channels (ch0009, ch000D and ch0000), the wired one with a device ID of "1013" has only two (ch0003 and ch0000). After discovery, every device with a ch000D shows up twice - once with its given name and once as "ABBXXXXXX/ch000D" (which doesn't do anything). Got it working with just exiting add_cover_device if the channel name is "ch000D", but that's just a very ugly bad hack.
> I've got some installed around here (mostly thermostat and cover/blinds actors), so I may be able to provide device IDs or whatever information or help needed. Just let me know.

Hi @crtee, I am trying to get DeviceID 2041 (Wireless roomthermostat) to work. I had it working before 2.3.0 by adding  "or device_id == '2041'" to row 814 of pfreeathome.py.
Now it is not working anymore. Did you manage to get it working and how did you do that?

Thank!

**Comment by crtee** [comment]
@dbrouwer1979 since Firmware 2.3.0 it's also broken here, couldn't find the time to look deeper into yet:

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 408, in _async_add_entity
    await entity.async_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 266, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 307, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 192, in state_attributes
    self.current_temperature,
  File "/config/custom_components/freeathome/climate.py", line 86, in current_temperature
    return float(self.thermostat_device.current_temperature)
TypeError: float() argument must be a string or a number, not 'NoneType'`

**Comment by crtee** [comment]
modifying pfreeathome.py like this: 
[diff.txt](https://github.com/jheling/freeathome/files/3609397/diff.txt)
at least displays them again (Disclaimer/Warning: ugly bad hack!).

But there are more issues with 2.3.0, for example if I turn on a F@H light in HA GUI it turns on, but the switch in the HA UI switches to off position after 1-2 seconds (the light stays on though).

**Comment by dbrouwer1979** [comment]
> modifying pfreeathome.py like this:
> [diff.txt](https://github.com/jheling/freeathome/files/3609397/diff.txt)
> at least displays them again (Disclaimer/Warning: ugly bad hack!).
> 
> But there are more issues with 2.3.0, for example if I turn on a F@H light in HA GUI it turns on, but the switch in the HA UI switches to off position after 1-2 seconds (the light stays on though).

I will try your 'ugly bad hack!' :)
I have the same error with light switch in HA turning off and light staying on.

**Comment by dbrouwer1979** [comment]
> > modifying pfreeathome.py like this:
> > [diff.txt](https://github.com/jheling/freeathome/files/3609397/diff.txt)
> > at least displays them again (Disclaimer/Warning: ugly bad hack!).
> > But there are more issues with 2.3.0, for example if I turn on a F@H light in HA GUI it turns on, but the switch in the HA UI switches to off position after 1-2 seconds (the light stays on though).
> 
> I will try your 'ugly bad hack!' :)
> I have the same error with light switch in HA turning off and light staying on.

The 'hack' did not work for me.

**Comment by jheling** [comment]
With the get-master-message.py you should see the messages that are from/to the sysap.
Maybe you can try the orginal Busch Jeager browser app to turn  some lights on and off and
use get-master-message.py to see which channels are used in the message. 
It is posible that they made a changed in the channels.

**Comment by Tho85** [comment]
The component has been reworked in the meantime. Feel free to test again and open a new issue if there are problems with your devices.
