### ISSUE TITLE
Error: NameError: name 'function_id' is not defined

### ISSUE THREAD

**Issue by thvd** [jheling/freeathome#194]
Broken because of merge of this commit: 

https://github.com/jheling/freeathome/pull/140/files

@jheling , @Tho85  I think this is throwing an exception because the function_id is missing from the `__init__` params (and more places i think) list: 

```

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/freeathome/__init__.py", line 84, in async_setup_entry
    await sysap.find_devices()
  File "/config/custom_components/freeathome/fah/pfreeathome.py", line 956, in find_devices
    await self.xmpp.find_devices(self._use_room_names, self._switch_as_x)
  File "/config/custom_components/freeathome/fah/pfreeathome.py", line 835, in find_devices
    self.add_device(fah_class, channel, channel_id, display_name + position_suffix + room_suffix, device_info, device_serialnumber, datapoints=datapoints, parameters = parameters)
  File "/config/custom_components/freeathome/fah/pfreeathome.py", line 604, in add_device
    function_id,
    ^^^^^^^^^^^
NameError: name 'function_id' is not defined

```

**Comment by jheling** [comment]
Your are right, i overlooked that function_id completely while resolving the merge conflict.
