### ISSUE TITLE
Update HA 2024.10.x und F@H 1.0.0

### ISSUE THREAD

**Issue by Beo666** [jheling/freeathome#206]
Guten Abend allerseits,
seit dem letzen Update auf HA 2024.10.0 und höher in Zusammenhang dem F@H 1.0.0 gehen die Dimmaktoren nicht mehr. Ich habe die Integration auch deinstalliert und neu angelegt (mit der Option Licht als Schalter und auch ohne diese Option). Jetzt sind einige Entitäten als Schalter UND Licht da... aber die Dimmer sind nur als Licht da und können nicht geschaltet werden.
![Unbenannt](https://github.com/user-attachments/assets/d603fb9b-5c83-466b-b98b-3390a6be05f0)

Edit: Jalousie-Aktoren und Raumthermostate haben auch keine Funktion mehr :(

Gruß
Lukas

**Comment by usi4** [comment]
Guten Morgen,
bei mir geht auch so einiges nicht mehr. HA 2024.10.2, OS 13.2, F@H 1.0.0.

![2024-10-17 07_53_21-Einstellungen – Home Assistant](https://github.com/user-attachments/assets/0a1c0d36-85c3-428f-87e4-1a79a97295b0)

Nach dem Update hat HA F@H noch mal gefunden mit gleicher IP ... 
Schalter in HA sind teilweise nicht verfügbar. Dimmer können eingeschaltet und gedimmt werden, aber nicht mehr ausgeschaltet werden. Der Status der Rollos und Jalousien in HA stimmt nicht. Über Schieberegler kann ich steuern, aber auch irgendwie nicht richtig.

Alles so durcheinander, dass ich es nicht strukturiert beschreiben kann - sorry.
Wenn ich noch Infos liefern soll, oder was testen soll, gerne Bescheid geben.

Grüße
Jörn

**Comment by NeoBlack** [comment]
It would be nice to use English in this project, the maintainer is from the Netherlands and if you expect any responses you should respect the fact that, English is the common language and international standard.

**Comment by NeoBlack** [comment]
I am running a free@home AP with firmware 3.3.2 and over 40 devices (including dim actors), 8 of which are wireless components (the window sensors).

Home Assistant is running with:
- Core: 2024.10.2
- Supervisor: 2024.10.2
- Operating System: 13.2
- Frontend: 20241002.3

The integration (jheling/freeathome) is installed via HACS. I have installed the latest commit: 6b0d309 (Version 1.0.0 is shown in the integration overview, but I guess you have maybe not the latest version? Check the commit hash in HACS)

I can control any device on my system without any issues. You could also try installing the latest version from the repository.

**Comment by jheling** [comment]
Hello, The double discover of this integration has to do with #204 .  I have tested this on a raspberry 3 with home assistant and saw the same effect. You should probably delete the two and then let home assistant rediscover the integration.  If in the past you did not use switch-as-x some of the devices have to be added again to your overview screen.  After a rediscover of the integration you should see all the devices/entities under settings, devices and services, Busch Jaeger/ABB Free@Home

**Comment by Beo666** [comment]
Good evening, everyone,
I must apologize for not writing my post in English. I had to downgrade to f89617b so that I could get my blinds, lights etc. back to work. The firmware of the AP is up to date and HA is version 2024.10.3. If more information is needed, please let me know.

Regards
Lukas

**Comment by NeoBlack** [comment]
Crazy, now I also have issues, but I could not narrow down the problem. 
What happens currently: 

- HA detected a new AP (with the same IP as the existing configuration)
- I have added it again and had two APs with the same IP, but the new configuration only shows me eight switches, nothing else. The old configuration provides 41 devices and 89 entities.
- One of my window sensors disappeared and is not returning, but it exists in free@home.

Here some logs
```
Logger: homeassistant.components.scene
Quelle: helpers/entity_platform.py:761
Integration: Szene (Dokumentation, Probleme)
Erstmals aufgetreten: 19:41:10 (125 Vorkommnisse)
Zuletzt protokolliert: 19:50:08

Platform freeathome does not generate unique IDs. ID FFFF4800000B/ch0000 already exists - ignoring scene.alles_aus
Platform freeathome does not generate unique IDs. ID FFFF4800000F/ch0000 already exists - ignoring scene.wohnzimmer_aus
Platform freeathome does not generate unique IDs. ID FFFF48030001/ch0000 already exists - ignoring scene.alle_jalousien_auf
Platform freeathome does not generate unique IDs. ID FFFF48000006/ch0000 already exists - ignoring scene.bad_aus
Platform freeathome does not generate unique IDs. ID FFFF48000005/ch0000 already exists - ignoring scene.heizung_aus

Logger: homeassistant.components.lock
Quelle: helpers/entity_platform.py:761
Integration: Schloss (Dokumentation, Probleme)
Erstmals aufgetreten: 19:41:10 (55 Vorkommnisse)
Zuletzt protokolliert: 19:50:08

Platform freeathome does not generate unique IDs. ID ABB*********/ch0014 already exists - ignoring lock.panel_tur_2
Platform freeathome does not generate unique IDs. ID ABB*********/ch0013 already exists - ignoring lock.panel_tur_3
Platform freeathome does not generate unique IDs. ID ABB*********/ch0012 already exists - ignoring lock.panel_tur_4
Platform freeathome does not generate unique IDs. ID ABB*********/ch0011 already exists - ignoring lock.panel_tur_5
Platform freeathome does not generate unique IDs. ID ABB*********/ch0010 already exists - ignoring lock.panel_tur

Logger: homeassistant.components.light
Quelle: helpers/entity_platform.py:761
Integration: Leuchte (Dokumentation, Probleme)
Erstmals aufgetreten: 19:41:10 (178 Vorkommnisse)
Zuletzt protokolliert: 19:50:08

Platform freeathome does not generate unique IDs. ID ABB*********/ch0001 already exists - ignoring light.wandlampen
Platform freeathome does not generate unique IDs. ID ABB*********/ch0000 already exists - ignoring light.wohnzimmer_2
Platform freeathome does not generate unique IDs. ID ABB*********/ch0003 already exists - ignoring light.lufter_bad
Platform freeathome does not generate unique IDs. ID ABB*********/ch0003 already exists - ignoring light.deckenlampe_arbeitszimmer_rechts
Platform freeathome does not generate unique IDs. ID ABB*********/ch0003 already exists - ignoring light.lufter_kuche

Logger: homeassistant.components.cover
Quelle: helpers/entity_platform.py:761
Integration: Abdeckung (Dokumentation, Probleme)
Erstmals aufgetreten: 19:41:10 (66 Vorkommnisse)
Zuletzt protokolliert: 19:50:08

Platform freeathome does not generate unique IDs. ID ABB*********/ch0003 already exists - ignoring cover.jalousie_kuche
Platform freeathome does not generate unique IDs. ID ABB*********/ch0003 already exists - ignoring cover.jalousie_arbeitszimmer_links
Platform freeathome does not generate unique IDs. ID ABB*********/ch0003 already exists - ignoring cover.schalter_jalousie_balkon
Platform freeathome does not generate unique IDs. ID ABB*********/ch0003 already exists - ignoring cover.jalousie_schlafzimmer
Platform freeathome does not generate unique IDs. ID ABB*********/ch0003 already exists - ignoring cover.jalousie_arbeitszimmer_rechts

Logger: homeassistant.components.climate
Quelle: helpers/entity_platform.py:761
Integration: Klima (Dokumentation, Probleme)
Erstmals aufgetreten: 19:41:10 (77 Vorkommnisse)
Zuletzt protokolliert: 19:50:08

Platform freeathome does not generate unique IDs. ID ABB*********/ch0000 already exists - ignoring climate.raumtemperaturregler_flur
Platform freeathome does not generate unique IDs. ID ABB*********/ch0000 already exists - ignoring climate.raumtemperaturregler_wc
Platform freeathome does not generate unique IDs. ID ABB*********/ch0000 already exists - ignoring climate.raumtemperaturregler_wohnzimmer
Platform freeathome does not generate unique IDs. ID ABB*********/ch0000 already exists - ignoring climate.raumtemperaturregler_bad
Platform freeathome does not generate unique IDs. ID ABB*********/ch0000 already exists - ignoring climate.raumtemperaturregler_az_links

Logger: homeassistant.components.climate
Quelle: components/climate/__init__.py:371
Integration: Klima (Dokumentation, Probleme)
Erstmals aufgetreten: 19:40:08 (105 Vorkommnisse)
Zuletzt protokolliert: 19:50:08

Entity None (<class 'custom_components.freeathome.climate.FreeAtHomeThermostat'>) implements HVACMode(s): heat_cool, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please report it to the author of the 'freeathome' custom integration

Logger: homeassistant.components.binary_sensor
Quelle: helpers/entity_platform.py:761
Integration: Binärsensor (Dokumentation, Probleme)
Erstmals aufgetreten: 19:41:10 (374 Vorkommnisse)
Zuletzt protokolliert: 19:50:08

Platform freeathome does not generate unique IDs. ID ABB*********/ch0000 already exists - ignoring binary_sensor.schlater_deckenlampe_schlafzimmer
Platform freeathome does not generate unique IDs. ID ABB*********/ch0000 already exists - ignoring binary_sensor.schalter_kuche_essplatz_l
Platform freeathome does not generate unique IDs. ID ABB*********/ch0000 already exists - ignoring binary_sensor.schalter_jalousie_schlafzimmer
Platform freeathome does not generate unique IDs. ID ABB*********/ch0001 already exists - ignoring binary_sensor.fenster_arbeitszimmer_rechts
Platform freeathome does not generate unique IDs. ID ABB*********/ch0000 already exists - ignoring binary_sensor.schalter_wohnzimmer_l
```

And here a maybe more helpfull log:
```
Logger: homeassistant.components.websocket_api.http.connection
Quelle: components/websocket_api/commands.py:245
Integration: Home Assistant WebSocket API (Dokumentation, Probleme)
Erstmals aufgetreten: 19:52:09 (7 Vorkommnisse)
Zuletzt protokolliert: 21:21:10

[139894867977712] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2761, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2804, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 996, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1068, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 639, in async_handle_light_off_service
    await light.async_turn_off(**filter_turn_off_params(light, params))
  File "/config/custom_components/freeathome/light.py", line 109, in async_turn_off
    await self.light_device.turn_off()
  File "/config/custom_components/freeathome/fah/devices/fah_light.py", line 57, in turn_off
    await self.client.set_datapoint(self.serialnumber, self.channel_id, self._datapoints[PID_SWITCH_ON_OFF], '0')
  File "/config/custom_components/freeathome/fah/pfreeathome.py", line 344, in set_datapoint
    await self.send_rpc_iq('RemoteInterface.setDatapoint',
slixmpp.exceptions.IqTimeout: <iq id="f3b8ac57009d429f8a234bb5631e0245" type="set" to="mrha@busch-jaeger.de/rpc" from="e589f095-7e05-4511-80d2-XXXXXXXXXXX@busch-jaeger.de/XXXXXXXX"><query xmlns="jabber:iq:rpc"><methodCall><methodName>RemoteInterface.setDatapoint</methodName><params><param><value><string>ABB*********X/ch0003/idp0000</string></value></param><param><value><string>0</string></value></param></params></methodCall></query></iq>
```

**Comment by usi4** [comment]
Hello.
I can confirm the solution proposed by jheling. I deleted the two integrations and installed the newly found one.
Thanks for the great support!

**Comment by NeoBlack** [comment]
I can also confirm that removing all configurations and adding the configuration again solves the issues; every automation and component works again.

**Comment by mattberlinHA** [comment]
Hi everybody,

the problems I encounter are different.

Since 10.2 the information coming from Free@Home do not seem to arrive in Home Assistant after a while. 
In other words, after freshly rebooting HA, I get an accurate temperature reading of a room thermostat. But after a while, it displays a constant value.
After returning to 10.1, it seems to work.

But how can I get it work on 10.3?

**Comment by Beo666** [comment]
Hello everybody,
I've found a solution for me, perhaps it'll work for your HA, too. I've deleted the integration under "Devices" and under HACS, then I've downloaded the actual commit with HACS. No downgrade needed.

Greets
Lukas

**Comment by NeoBlack** [comment]
I still have issues with the latest commit; I also tried removing the whole integration and installing it again.
Now, I am missing three devices and the protocol shows errors again:

<img width="1006" alt="Bildschirmfoto 2024-10-19 um 19 33 03" src="https://github.com/user-attachments/assets/581d6691-4b56-442e-a29d-44ad11ed25ce">

What I did until now:
- Uninstalled integration
- Checked that the folder was removed
- Removed the user/password from the configuration.yaml
- installed integration via HACS again
- configured integration via UI again

Result:
- 39 of 42 devices are available, 82 of 89 entities are available
- A lot of automation does not work anymore

Any other ideas?

**Comment by jheling** [comment]
Can you find the entities with the double names in Home Assistant? Are they active or greyed out?  Maybe you have to delete those double entities and then restart Home Assistant

**Comment by NeoBlack** [comment]
Hell, what a hassle...
- Deinstalled integration complete
- removed configuration
- restart
- Install integration again
- added all devices again
- Fix / Update automations and scripts.

Now it looks like everything works again.

**Comment by guerda** [comment]
> * restart

Thanks @NeoBlack for the details, this is helpful and fixed it for me.

One important aspect: If you are running Home Assistant in Docker, the restart from the UI does not seem to be enough. I had to restart it via the docker system.
