### ISSUE TITLE
f@h reacts slowly or not at all

### ISSUE THREAD

**Issue by jws75** [jheling/freeathome#209]
Hello, I updated my f@h access point to firmware version 3.4.1- 13444.
Since then I have had this problem:
 When I want to switch f@h components in Homeassistant or use states of f@h devices as triggers for automations, they work with a time delay or not at all.
Does anyone know this?

**Comment by jheling** [comment]
I am still on an old version of the firmware as i have a version 1 of the sysap. 
Maybe the new version of the integration has some issues with this integration. 
Does the log of Home Assistant show any FreeAtHome  errors?

**Comment by jws75** [comment]
Hmm, I've never used the HA logs. I'll have to look to see if I can find anything. Where can I find them?

**Comment by jheling** [comment]
You can find it under Settings, System, Logs. First the condensed log is shown. In the upper right corner of the screen there are three dots.  Here you can select the raw logs. There is also an option to download the logs. 
Maybe is its better to restart your system first before looking at the logs.  Otherwise these logs can become very big. You can restart with Settings, System and then the button in the upper right corner.

**Comment by jws75** [comment]
Okay, thanks, I'll take a look.
But in the meantime I think it's more likely that it's because of f@h, because it's also slow from Alexa, for example.

**Comment by henning89** [comment]
I have similar issues now as well. free@home SysAP 1.0 with firmware 3.4.1 and Home Assistant 2025.01.
Same issues before with free@home firmware 3.4.0 and Home Assistant 2024.12 

Some error log below if it helps:

`[31m2025-01-05 18:20:45.057 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140069270952048] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2795, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2838, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1006, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1078, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/freeathome/cover.py", line 168, in async_set_cover_position
    await self.cover_device.set_cover_position(position)
  File "/config/custom_components/freeathome/fah/devices/fah_cover.py", line 114, in set_cover_position
    await self.client.set_datapoint(self.serialnumber, self.channel_id, dp, str(abs(100 - position)))
  File "/config/custom_components/freeathome/fah/pfreeathome.py", line 344, in set_datapoint
    await self.send_rpc_iq('RemoteInterface.setDatapoint',
                           name, command, callback=self.rpc_callback)
slixmpp.exceptions.IqTimeout: <iq id="ca78d6c6d509436482d18dc5eb8d6dcb" type="set" to="mrha@busch-jaeger.de/rpc" from="installer@busch-jaeger.de/f4b38900"><query xmlns="jabber:iq:rpc"><methodCall><methodName>RemoteInterface.setDatapoint</methodName><params><param><value><string>ABB200A82A51/ch0000/idp0002</string></value></param><param><value><string>100</string></value></param></params></methodCall></query></iq>[0m
[31m2025-01-05 18:20:47.378 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140069270952048] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2795, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2838, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1006, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1078, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/freeathome/cover.py", line 168, in async_set_cover_position
    await self.cover_device.set_cover_position(position)
  File "/config/custom_components/freeathome/fah/devices/fah_cover.py", line 114, in set_cover_position
    await self.client.set_datapoint(self.serialnumber, self.channel_id, dp, str(abs(100 - position)))
  File "/config/custom_components/freeathome/fah/pfreeathome.py", line 344, in set_datapoint
    await self.send_rpc_iq('RemoteInterface.setDatapoint',
                           name, command, callback=self.rpc_callback)
slixmpp.exceptions.IqTimeout: <iq id="22407e40fe6846f08490d71133d3db8c" type="set" to="mrha@busch-jaeger.de/rpc" from="installer@busch-jaeger.de/f4b38900"><query xmlns="jabber:iq:rpc"><methodCall><methodName>RemoteInterface.setDatapoint</methodName><params><param><value><string>ABB200A82A51/ch0001/idp0002</string></value></param><param><value><string>100</string></value></param></params></methodCall></query></iq>[0m
[36m2025-01-05 18:20:50.162 DEBUG (MainThread) [custom_components.freeathome.fah.pfreeathome] received datapoint ABB700DC54E7/ch0000/odp0001 = 0[0m
`
