### ISSUE TITLE
Authentication failed after update to homeassistant 2024.12

### ISSUE THREAD

**Issue by joconcepts** [jheling/freeathome#212]
After updating to homeassistant 2024.12 the integration broken:

```
 2024-12-09 07:07:20.709 ERROR (MainThread) [custom_components.freeathome.fah.pfreeathome] Free@Home : authentication failed, probably wrong password                               │
│ 2024-12-09 07:07:20.709 ERROR (MainThread) [slixmpp.features.feature_mechanisms.mechanisms] No appropriate login method.                                                           │
│ 2024-12-09 07:07:20.711 WARNING (MainThread) [custom_components.freeathome.fah.pfreeathome] Connection with SysAP lost   
```
Reverting to older homeassistant version fixed the issue. The integration is installed via HACS and on the latest commit.

**Comment by joconcepts** [comment]
I use the docker container, maybe there is something different?

**Comment by bwolkerstorfer** [comment]
I can reproduce the issue of @joconcepts on my installation using Kubernetes. Still trying to pinpoint the issue but I suspect that it could be related to the upgrade of `aiohttp` or something else that relies on OS stuff (i.e. root CA) since I have 2 other integrations (Gardena und AsusRouter) that have a similar issue.

**Comment by joconcepts** [comment]
I also saw this error in my logs:

```
2024-12-11 07:52:46.863 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to load_default_certs with args (<ssl.SSLContext object at 0x7ff57b4ab8d0>, <Purpose.SERVER_AUTH: _ASN1Object(nid=129, shortname='serverAuth', longname='TLS Web Server Authentication', oid='1.3.6.1.5.5.7.3.1')>) inside the event loop by custom integration 'freeathome' at custom_components/freeathome/fah/pfreeathome.py, line 220: slixmpp.ClientXMPP.__init__(self, jid, password, sasl_mech='SCRAM-SHA-1') (offender: /usr/local/lib/python3.12/ssl.py, line 713: context.load_default_certs(purpose)), please report it to the author of the 'freeathome' custom integration
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_default_certs
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 783, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 546, in async_setup
    await self.__async_setup_with_context(hass, integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/freeathome/__init__.py", line 82, in async_setup_entry
    await sysap.connect()
  File "/config/custom_components/freeathome/fah/pfreeathome.py", line 906, in connect
    self.xmpp = Client(self._jid, self._password, self._host, self._port, fahversion, iterations, salt, self.reconnect)
  File "/config/custom_components/freeathome/fah/pfreeathome.py", line 220, in __init__
    slixmpp.ClientXMPP.__init__(self, jid, password, sasl_mech='SCRAM-SHA-1')
    ```

**Comment by joconcepts** [comment]
Maybe it helps to update slixmpp
https://codeberg.org/poezio/slixmpp/releases/tag/slix-1.8.5

**Comment by guerda** [comment]
I also have the same issue and it happened during the last three updates, too. Only thing that worked is reinstalling the integration completely.

Important: on docker setups, I had to restart the docker container. Restarting from the UI was not enough.

**Comment by bwolkerstorfer** [comment]
A quick status update from my side about my debugging effort:
* I have configured my HA instance to debug logging to capture the SASL auth messages, the messages look generally good to me, but I have not verified the password hashing results which I will do shortly.
* Also the challenge/response flow seems to work as expected on HA 2024.12.4.
* Interestingly I cannot see any logs produced by `SaslHandler` even with HA on full debug mode.

Generally from debugging I would say that looks like some cryptographic issue since the general XMPP messaging seems to work and the SysApp responds properly, hope to be able to continue later today and finally find the culprit here.

**Comment by bwolkerstorfer** [comment]
Could by related to `pynacl 1.5` not officially supporting `python 3.13` (HA was upgraded to it in `2024.12`) - have seen other projects having also issues - might be worth creating a dev build of `1.6.0` and try it locally.

**Comment by bwolkerstorfer** [comment]
I am not 100% up with `SCRAM-SHA1` on FAH but for what I have know from the spec the initial message format is
```
n,,n=<JID>,r=<CLIENT_NONCE>
```
and the final message format is:
```
c=biws,r=<SERVER_NONCE>,p=<CLIENT_PROOF_BASE64>
```

Here are the messages the integration sent on my installation (base64-decoded from the HA logs):
```
y,,n=d4d13250-e5a3-4b6a-8c9d-0062bd1716f5,r=653836779481925
```
and
```
c=eSws,r=653836779481925nVKvzbTeqM8=,p=RtnHPeEZ2kvu/eZvKH5+9X5CeWw=
```

**Comment by guerda** [comment]
Thanks for diving into this so deeply! What surprises me is that after a hard restart, my problem was fixed. Could it be that some dependencies (like pynacl or pycrypto) are loaded differently?

**Comment by bwolkerstorfer** [comment]
I am running on k8s and also tried to uninstall an reinstall without any change to the error, but I will try to purge all deps to check if that fixes it, thanks for pointing out the hard restart on Docker.

**Comment by bwolkerstorfer** [comment]
I have setup an full dev-environment now and can confirm that this is only related to containerized (Docker, k8s) environments, so seems to be related to something a container cannot provide that another installation method provides.

**Comment by guerda** [comment]
I had the same problem with the newest update to c85fe4d. I was on HA 2024.10 and a hard restart didn't help. Updating to 2024.12.5 helped to fix this for me. Let's see if this stays with the next fah update

**Comment by bwolkerstorfer** [comment]
Since I had time and and got (myself 🙄 ) some hardware for 🎄, I decided to switch to a new setup using Proxmox and and host HAOS as VM there which solves this issue and also other common issues I had with the upgrade flow.

**Comment by joconcepts** [comment]
Did anyone get that to work with k8s? I mean, restarting the pod causes a new pod to be created, so for every image update a hard restart is done. Maybe some of you have some steps to fix that issue with latest HA update?

**Comment by guerda** [comment]
Yet another information: after an update of HACS, I again encountered the problem. I had to restart twice in docker and then fah works again.

I created a log for the time between. I just have to review if something sensitive is there.

**Comment by guerda** [comment]
Here's the log file: https://termbin.com/0m26

**Comment by guerda** [comment]
I monitored the situation over the last month. If I restart the docker container, free at home locks up. If I stop the container, wait a few seconds (10 s) and then start the container again, no account lockout happens.

Does that help in finding a root cause?

**Comment by jheling** [comment]
@guerda. When you restart Home Assistant the connection to Free@Home is gone. Maybe it takes Free@Home some time to find out the other end is gone.  Is the machine you are running Home Assistant  on a fast machine? 

I am thinking of logging the custom component out  when Home Assistant does a  reset. then a account lockup should not happen.

**Comment by guerda** [comment]
I'm running it on a raspberry pi 4, CPU is not a bottleneck according to my monitoring. RAM might be.

I can check the system again during a restart of HA.

**Comment by jheling** [comment]
@guerda Could you try #233?

**Comment by guerda** [comment]
I will try to do this the next couple of days, thank you for working on this!

**Comment by guerda** [comment]
I applied the patch from the pull request via git apply and it changed both files. I had stopped HA before and removed __pycache__. After that I started it, shut down but the message doesn't show up in my log. Unfortunately the authentication error still persists.

I will try again with a bit more details.


What I stumbled upon is this error message which I haven't seen before:

```
2025-04-19 12:48:49.830 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to load_default_certs with args (<ssl.SSLContext object at 0x7f612bcd40>, <Purpose.SERVER_AUTH: _ASN1Object(nid=129, shortname='serverAuth', longname='TLS Web Server Authentication', oid='1.3.6.1.5.5.7.3.1')>) inside the event loop by custom integration 'freeathome' at custom_components/freeathome/fah/pfreeathome.py, line 220: slixmpp.ClientXMPP.__init__(self, jid, password, sasl_mech='SCRAM-SHA-1') (offender: /usr/local/lib/python3.13/ssl.py, line 722: context.load_default_certs(purpose)), please report it to the author of the 'freeathome' custom integration             For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_default_certs                            Traceback (most recent call last):                File "<frozen runpy>", line 198, in _run_module_as_main                                         File "<frozen runpy>", line 88, in _run_code    File "/usr/src/homeassistant/homeassistant/__main__.py", line 227, in <module>                    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 213, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 154, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 712, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 683, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2040, in _run_once
    handle._run()
  File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 896, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 662, in async_setup
    await self.__async_setup_with_context(hass, integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 751, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/freeathome/__init__.py", line 82, in async_setup_entry
    await sysap.connect()
  File "/config/custom_components/freeathome/fah/pfreeathome.py", line 906, in connect
    self.xmpp = Client(self._jid, self._password, self._host, self._port, fahversion, iterations, salt, self.reconnect)
  File "/config/custom_components/freeathome/fah/pfreeathome.py", line 220, in __init__
    slixmpp.ClientXMPP.__init__(self, jid, password, sasl_mech='SCRAM-SHA-1')
```

**Comment by guerda** [comment]
Update: the disconnect appears in the log file now, this is how it looks like for me during a `docker stop`

```
2025-04-22 13:11:54.004 INFO (MainThread) [custom_components.freeathome.fah.pfreeathome] Detecting shutdown home assistant
2025-04-22 13:11:54.004 INFO (MainThread) [custom_components.freeathome.fah.pfreeathome] Disconnecting connection with Free@Home
2025-04-22 13:11:54.080 INFO (MainThread) [slixmpp.xmlstream.xmlstream] connection_lost: (None,)
2025-04-22 13:11:54.084 WARNING (MainThread) [custom_components.freeathome.fah.pfreeathome] Connection with SysAP lost
```

unfortunately, the lock still appears. The integration comes up with an error that the setup didn't work.
The last error in the logs is the one shown in my previous comment

**Comment by guerda** [comment]
While the warning about the blocking call still appears with #233, the user does not lock up anymore. For me, this works fine now with the newest version of Home Assistant (2025.4.3).

Thank you, @jheling for your work and your persistence to keep investigating it.

**Comment by EnricoBilla** [comment]
@jheling Version 1.0.2 with #233 is working correctly here on HA v2025.4.3
Thanks for your work debugging and fixing the problem!
