### ISSUE TITLE
Update causes user being locked 

### ISSUE THREAD

**Issue by guerda** [jheling/freeathome#213]
The last three updates had the same annoying consequence: my user in the free at home system AP is getting locked. 
I don't know why but it happens 

My only solution is to remove the integration completely, uninstall it and then install it again. This is very annoying and prevents me using the integration at all.

I think it relates to #212.

**Comment by jheling** [comment]
Hello, Do you get any errors in the log?

**Comment by guerda** [comment]
Sorry for replying so late. Basically, after the update this happens in the log file:

```
2024-12-11 20:18:31.884 INFO (MainThread) [slixmpp.features.feature_mechanisms.mechanisms] Authentication failed: not-authorized
2024-12-11 20:18:31.884 ERROR (MainThread) [custom_components.freeathome.fah.pfreeathome] Free@Home : authentication failed, probably wrong password
2024-12-11 20:18:31.884 ERROR (MainThread) [slixmpp.features.feature_mechanisms.mechanisms] No appropriate login method.
2024-12-11 20:18:31.913 INFO (MainThread) [slixmpp.xmlstream.xmlstream] connection_lost: (None,)
2024-12-11 20:18:31.915 WARNING (MainThread) [custom_components.freeathome.fah.pfreeathome] Connection with SysAP lost
2024-12-11 20:18:34.169 INFO (MainThread) [slixmpp.features.feature_mechanisms.mechanisms] Authentication failed: not-authorized
2024-12-11 20:18:34.170 ERROR (MainThread) [custom_components.freeathome.fah.pfreeathome] Free@Home : authentication failed, probably wrong password
2024-12-11 20:18:34.170 ERROR (MainThread) [slixmpp.features.feature_mechanisms.mechanisms] No appropriate login method.
2024-12-11 20:18:34.178 INFO (MainThread) [slixmpp.xmlstream.xmlstream] connection_lost: (None,)
2024-12-11 20:18:34.181 WARNING (MainThread) [custom_components.freeathome.fah.pfreeathome] Connection with SysAP lost
2024-12-11 20:18:36.434 INFO (MainThread) [slixmpp.features.feature_mechanisms.mechanisms] Authentication failed: not-authorized
2024-12-11 20:18:36.434 ERROR (MainThread) [custom_components.freeathome.fah.pfreeathome] Free@Home : authentication failed, probably wrong password
2024-12-11 20:18:36.434 ERROR (MainThread) [slixmpp.features.feature_mechanisms.mechanisms] No appropriate login method.
2024-12-11 20:18:36.436 INFO (MainThread) [slixmpp.xmlstream.xmlstream] connection_lost: (None,)
2024-12-11 20:18:36.437 WARNING (MainThread) [custom_components.freeathome.fah.pfreeathome] Connection with SysAP lost
2024-12-11 20:18:38.697 INFO (MainThread) [slixmpp.features.feature_mechanisms.mechanisms] Authentication failed: not-authorized
2024-12-11 20:18:38.697 ERROR (MainThread) [custom_components.freeathome.fah.pfreeathome] Free@Home : authentication failed, probably wrong password
2024-12-11 20:18:38.697 ERROR (MainThread) [slixmpp.features.feature_mechanisms.mechanisms] No appropriate login method.
2024-12-11 20:18:38.700 INFO (MainThread) [slixmpp.xmlstream.xmlstream] connection_lost: (None,)
2024-12-11 20:18:38.701 WARNING (MainThread) [custom_components.freeathome.fah.pfreeathome] Connection with SysAP lost
2024-12-11 20:18:41.012 INFO (MainThread) [slixmpp.features.feature_mechanisms.mechanisms] Authentication failed: not-authorized
2024-12-11 20:18:41.012 ERROR (MainThread) [custom_components.freeathome.fah.pfreeathome] Free@Home : authentication failed, probably wrong password
2024-12-11 20:18:41.012 ERROR (MainThread) [slixmpp.features.feature_mechanisms.mechanisms] No appropriate login method.
2024-12-11 20:18:41.015 INFO (MainThread) [slixmpp.xmlstream.xmlstream] connection_lost: (None,)
2024-12-11 20:18:41.016 WARNING (MainThread) [custom_components.freeathome.fah.pfreeathome] Connection with SysAP lost
2024-12-11 20:18:43.368 INFO (MainThread) [slixmpp.features.feature_mechanisms.mechanisms] Authentication failed: temporary-auth-failure
2024-12-11 20:18:43.368 ERROR (MainThread) [custom_components.freeathome.fah.pfreeathome] Free@Home : authentication failed, probably wrong password
2024-12-11 20:18:43.369 ERROR (MainThread) [slixmpp.features.feature_mechanisms.mechanisms] No appropriate login method.
```

I suspect the reason for the switch from `not-authorized` and `temporary-auth-failure` is that the FAH Sys AP locks users out after too many attempted logins.

Earlier in the log, I find a log (> 1000) occurences of this, not sure if this related anyhow:

```
2024-12-11 00:00:16.480 ERROR (MainThread) [slixmpp.stanza.rootstanza] Error handling {jabber:client}message stanza
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/slixmpp/xmlstream/xmlstream.py", line 1107, in handler_callback_routine
    except Exception as e:
        ^^^^^^^^^^^^^^
  File "/config/custom_components/freeathome/fah/pfreeathome.py", line 439, in pub_sub_callback
    xmessage = self.saslhandler.crypto.decryptPubSub(args[0])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/freeathome/fah/crypto.py", line 210, in decryptPubSub
    if nonceNumber < sequenceNumber:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Hope that helps.

**Comment by guerda** [comment]
Closed in favor of #212
