### ISSUE TITLE
binary sensor log message

### ISSUE THREAD

**Issue by bartdorlandt** [jheling/freeathome#49]
Since the latest change(s), i'm getting the following message about the binary sensor.

`2020-04-22 22:23:34 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up freeathome platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 186, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 295, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 423, in _async_add_entity
    raise HomeAssistantError(f"Invalid entity id: {entity.entity_id}")
homeassistant.exceptions.HomeAssistantError: Invalid entity id: binary_sensor.
2020-04-22 22:23:35 ERROR (MainThread) [homeassistant.core] Error doing job: Exception in callback async_setup_entity_restore.<locals>._write_unavailable_states(<Event homeassistant_start[L]>) at /usr/src/homeassistant/homeassistant/helpers/entity_registry.py:528
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 560, in _write_unavailable_states
    states.async_set(entry.entity_id, STATE_UNAVAILABLE, attrs)
  File "/usr/src/homeassistant/homeassistant/core.py", line 994, in async_set
    state = State(entity_id, new_state, attributes, last_changed, None, context)
  File "/usr/src/homeassistant/homeassistant/core.py", line 730, in __init__
    f"Invalid entity id encountered: {entity_id}. "
homeassistant.exceptions.InvalidEntityFormatError: Invalid entity id encountered: binary_sensor.. Format should be <domain>.<object_id>`

All seems to be running still though.

**Comment by jheling** [comment]
Yes, i have 2 raspberry pi's with HA , the same custom components and one is showing the error, the other not. First thought whas the difference in HA version, but after upgrading the error remained.
