### ISSUE TITLE
Could not parse JSON content

### ISSUE THREAD

**Issue by JvD12** [jheling/freeathome#83]
I found several errors messages in the log file during debugging another home assistant integration:

`2020-12-12 14:55:56 INFO (MainThread) [custom_components.freeathome.lock] FreeAtHome setup lock controll
2020-12-12 14:55:56 INFO (MainThread) [custom_components.freeathome.climate] FreeAtHome setup thermostat
2020-12-12 14:55:57 ERROR (SyncWorker_2) [homeassistant.util.json] Could not parse JSON content: /config/custom_components/freeathome/translations/nl.json
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 32, in load_json
    return json.loads(fdesc.read())  # type: ignore
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 28 column 5 (char 802)
2020-12-12 14:55:57 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [2943349256] Error handling message: Expecting property name enclosed in double quotes: line 28 column 5 (char 802)
2020-12-12 14:55:57 ERROR (SyncWorker_0) [homeassistant.util.json] Could not parse JSON content: /config/custom_components/freeathome/translations/nl.json
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 32, in load_json
    return json.loads(fdesc.read())  # type: ignore
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 28 column 5 (char 802)
2020-12-12 14:55:57 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [2953522528] Error handling message: Expecting property name enclosed in double quotes: line 28 column 5 (char 802)
2020-12-12 14:55:57 ERROR (SyncWorker_4) [homeassistant.util.json] Could not parse JSON content: /config/custom_components/freeathome/translations/nl.json
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 32, in load_json
    return json.loads(fdesc.read())  # type: ignore
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 28 column 5 (char 802)` 

I tested it with the software just downloaded from this repository.

**Comment by Tho85** [comment]
There is a syntax error in `nl.json`, I've added a fix in #84

**Comment by Gersh1970** [comment]
> There is a syntax error in `nl.json`, I've added a fix in #84
 I can confirm this fixes it
