### ISSUE TITLE
Problems with integration  FreeatHome in Homeassistant

### ISSUE THREAD

**Issue by Rafael8681** [jheling/freeathome#92]
Hi,
It tried to implement Freut Home in Homassistant.
I have Version 2.6.1 on my SAP.
I got following logs

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 248, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/freeathome/__init__.py", line 75, in async_setup_entry
    await sysap.find_devices()
  File "/config/custom_components/freeathome/fah/pfreeathome.py", line 886, in find_devices
    await self.xmpp.find_devices(self._use_room_names)
  File "/config/custom_components/freeathome/fah/pfreeathome.py", line 776, in find_devices
    self.add_device(fah_class, channel, channel_id, display_name + position_suffix + room_suffix, device_info, device_serialnumber, datapoints=datapoints, parameters = parameters)
  File "/config/custom_components/freeathome/fah/pfreeathome.py", line 564, in add_device
    device = fah_class(
TypeError: __init__() got an unexpected keyword argument 'parameters'

I could integrate Free at Home but there are no devices shown.

<img width="626" alt="Bildschirmfoto 2021-03-15 um 09 30 35" src="https://user-images.githubusercontent.com/80674922/111124837-4035d300-8571-11eb-8a21-46296f168282.png">

Thanks for your Help

**Comment by Rafael8681** [comment]
An i could also not use the dump function.

**Comment by Tho85** [comment]
@Rafael8681 Oops, sorry, looks like the last update broke the component startup for sensors. I've fixed it in #93 . Until it is merged, feel free to use the fixed version [from my repository](https://github.com/Tho85/freeathome/tree/Tho85/fix-sensor-parameters).

**Comment by Rafael8681** [comment]
@Tho85  Thanks,not it works. Perfect Help.
